### ISSUE TITLE
Create a Crowdin project

### ISSUE THREAD

**Issue by ImRodry** [SmajloSlovakian/MinecraftSplashTextTranslation#3]
Hey! I recently discovered this project through one of my friends and it seems really interesting, but not practical to contribute to at the moment. I would like to suggest creating a project at https://crowdin.com (it's free for open-source projects) and uploading the files there so that it's easier for translators to translate and for new people to find the project. I have a lot of experience working with C2rowdin projects so if you need my help, just reach out to me here or on Discord: Rodry#4020

**Comment by SmajloSlovakian** [comment]
hello! i tried crowdin once and i didnt really see the free thing, it put me in a free trial, and so from then i know that i dont know how to do things in crowdin... you can reach out to me in loki's society and minecraft translators discord servers, ik youre there :) i will try the crowdin again in a few days and if i need help, i will ask... thx

**Comment by SmajloSlovakian** [comment]
Done :)
